# Generated by Django 4.1.2 on 2022-10-18 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_fecha_nacimiento_persona_fecha_creacion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Persona',
            new_name='Humano',
        ),
    ]
